/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RateIdRouteImport } from './routes/rate.$id'
import { Route as ApiDownloadCodeRouteImport } from './routes/api.download-code'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RateIdRoute = RateIdRouteImport.update({
  id: '/rate/$id',
  path: '/rate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadCodeRoute = ApiDownloadCodeRouteImport.update({
  id: '/api/download-code',
  path: '/api/download-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/download-code': typeof ApiDownloadCodeRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/download-code': typeof ApiDownloadCodeRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/download-code': typeof ApiDownloadCodeRoute
  '/rate/$id': typeof RateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/download-code' | '/rate/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/download-code' | '/rate/$id'
  id: '__root__' | '/' | '/dashboard' | '/api/download-code' | '/rate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiDownloadCodeRoute: typeof ApiDownloadCodeRoute
  RateIdRoute: typeof RateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate/$id': {
      id: '/rate/$id'
      path: '/rate/$id'
      fullPath: '/rate/$id'
      preLoaderRoute: typeof RateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-code': {
      id: '/api/download-code'
      path: '/api/download-code'
      fullPath: '/api/download-code'
      preLoaderRoute: typeof ApiDownloadCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiDownloadCodeRoute: ApiDownloadCodeRoute,
  RateIdRoute: RateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
